backend:
  name: github
  repo: ferugi/ferugi.com
  branch: master
  base_url: # env var: NETLIFY_AUTH_BASE_URL 
  auth_endpoint: api/netlify-auth/begin
media_folder: public/images
public_folder: public/images
site_url: # env var: NETLIFY_BASE_URL
show_preview_links: true
collections:
  - label: "Pages"
    name: "pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Author", name: "author", widget: "string"}
        - { label: "Site Title", name: "siteTitle", widget: "string"}
        - label: 'Contact Data'
          name: "contactData"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
            - { label: "Fontawesome Icon Class", name: "faIcon", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}

    - label: "CV"
      name: cv
      file: "content/cv.md"
      fields:
        - { label: "Full Name", name: "fullName", widget: "string"}
        - { label: "Title", name: "title", widget: "string"}
        - label: "Contact Details"
          name: "contactDetails"
          widget: "object"
          collapsed: true
          fields:
            - { label: "Email Address", name: "email", widget: "string"}
            - { label: "Phone Number", name: "phone", widget: "string"}
            - { label: "LinkedIn Slug", name: "linkedIn", widget: "string"}
            - { label: "Location", name: "location", widget: "string"}
        - { label: "Summary", name: "summary", widget: "markdown"}
        
  - label: "Blog Posts"
    name: "blog-posts"
    folder: "content/blog/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Facebook Comment Link", name: "fbcommentlink", widget: "hidden" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
