blogtitle: Blog

links:
    email: me@ferugi.com
    socialmedia:
        Facebook: http://facebook.com/ferugi
        LinkedIn: https://www.linkedin.com/in/ferugi
        GitHub: https://github.com/ferugi
        #twitch: https://www.twitch.tv/furiosustv

comments:
    using: facebook     #   "facebook" or "disqus"
    facebook:
        appId: 929230953797958
        count: 5
        width: 512
        colorscheme: light