bio:
    title: Ferugi El Heri
    description: I'm into tech, coding, weightlifing, and climbing

links:
    email: me@ferugi.com
    socialmedia:
        facebook: http://facebook.com/ferugi
        github: https://github.com/ferugi
        linkedin: https://www.linkedin.com/in/ferugi
        #twitch: https://www.twitch.tv/furiosustv

