menu:
  Home:
  About Me: about

showindex: true

widgets:
- category
- tagcloud

excerpt_link: Read More

twitter:
  username: ferugielheri
  show_replies: true
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: false

fancybox: true

google_analytics:
rss:

comment_provider: facebook

# Facebook comment
facebook:
  appid: 929230953797958
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
